### ISSUE TITLE
Is it a bug that random selection of input nodes may result in duplication?

### ISSUE THREAD

**Issue by neverland7** [netneurolab/conn2res#27]
![image](https://github.com/netneurolab/conn2res/assets/44805723/a54e5a05-907e-4b80-9769-2ac6a2942c03)

**Comment by anaston** [comment]
Thanks for pointing it out. Indeed, it is a bug, I also came across it recently but haven't had the time to look into it properly. I will try to make a fix for it asap.

**Comment by neverland7** [comment]
Thank you for your prompt fix！
