### ISSUE TITLE
The parcellation of the human connectome

### ISSUE THREAD

**Issue by AlbertXTang** [netneurolab/conn2res#34]
Hi, where can we find image file and its index file of the Desikan Killiany atlas which was used to parcellated human connectome and included 1015 brain regions according the statement in the tutorial.py?

**Comment by janett105** [comment]
you can find in here : https://github.com/LTS5/cmp_nipype

**Comment by AlbertXTang** [comment]
Thank you! I really&nbsp;appreciate your help!&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "netneurolab/conn2res"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月5日(星期二) 中午1:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [netneurolab/conn2res] The parcellation of the human connectome (Issue #34)





 
you can find in here : https://github.com/LTS5/cmp_nipype
