### ISSUE TITLE
There was an issue running the file tutorial,this issue also occurs in the file tutorial.ipynb

### ISSUE THREAD

**Issue by howmuchyouwillrisk** [netneurolab/conn2res#45]
![微信图片_20240412161028](https://github.com/netneurolab/conn2res/assets/141500030/761901ae-b497-47ef-beca-8572de6816ae)
Thank you for providing the toolbox, however, there are some issues that prevent us from using it well.

**Comment by estefanysuarez** [comment]
Hi @howmuchyouwillrisk , thanks for your interest in the toolbox.

**Comment by estefanysuarez** [comment]
Hi @howmuchyouwillrisk , thanks for your interest in the toolbox!

**Comment by estefanysuarez** [comment]
Hi @howmuchyouwillrisk , thanks for your interest in the toolbox!
We apologize for this. In order to help you, it would be nice if I could see how you are running the code. Did you change anything from the original settings?

**Comment by howmuchyouwillrisk** [comment]
I just ran the tutorial. py file without making any changes. It appears that there is an issue with the (# visualize reserve states) and (# visualize diagnostic curves) in the file. If they are commented out, the code can run normally.Thank you！

**Comment by sreguyal** [comment]
Hi, I had the same issue when running tutorial.ipynb. The issue goes away when I comment out the lines 328, 481 in plotting.py: `# """.format(**_figs_params_docs)` and then close the docstring comment with `"""`.
