### ISSUE TITLE
Where can I get the three files connectivity.npy, cortical.npy, rsn_mapping.npy?

### ISSUE THREAD

**Issue by Adai2020** [netneurolab/conn2res#9]
Where can I get the three files connectivity.npy, cortical.npy, rsn_mapping.npy?

**Comment by janett105** [comment]
I have same issue

when I run tutorial, there is an error in 

# load connectivity data of one subject
conn = Conn(subj_id=0)

there is no 'examples' file

**Comment by janett105** [comment]
Hi estefanysuarez,

Thanks for your reply.
I added a folder 'data' in 'examples' folder and downloaded 'data.zip' in https://zenodo.org/record/4776453#.Yd9AuS_72N8 that you mentioned in issue#1.
But there is no 'connectibity.npy'file in 'data.zip', so I want to ask what I have to do. 

-----Original Message-----

**Comment by estefanysuarez** [comment]
Hi Adai2020, 

If you downloaded the folder `data` from Zenodo, then here you will find the corresponding files:

```
connectivity.npy ---> connectivity/individual/human_500.npy
cortical.npy ---> cortical/cortical_human_500.npy
rsn_mapping.npy ---> rsn_mapping/rsn_human_500.npy
```

Just select those three files, change their names to `connectivity.npy`, `cortical.npy` and `rsn_mapping.npy`, respectively, and place them in the `data` folder inside the `examples` folder and it should work.

Let me know if it works!

**Comment by neverland7** [comment]
It works! but if running it directly, it throws an error:

InvalidParameterError: The 'adjusted' parameter of balanced_accuracy_score must be an instance of 'bool', an instance of 'numpy.bool_' or an instance of 'int'. Got None instead.

simply assign a value of True or False to the 'adjusted' parameter, and the code will run without errors.
